package com.laravelshao.common.test.mapper;

import com.laravelshao.common.test.model.Order;
import com.laravelshao.common.test.model.OrderExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Fri Oct 04 20:09:24 CST 2019
     */
    int updateByPrimaryKey(Order record);

    /**
     * 获取指定时间未支付订单列表
     *
     * @param time
     * @param shardingTotalCount
     * @param shardingItem
     * @return
     */
    List<Order> getOrder(Date time, int shardingTotalCount, int shardingItem);

    /**
     * 取消订单
     *
     * @param orderId
     * @param updateTime
     * @param status
     * @param updateUser
     * @param updateNow
     * @return
     */
    int cancelOrder(Integer orderId, Date updateTime, int status, String updateUser, Date updateNow);
}