package com.laravelshao.common.test.mapper;

import com.laravelshao.common.test.model.TmallOrder;
import com.laravelshao.common.test.model.TmallOrderExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TmallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    long countByExample(TmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int deleteByExample(TmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int insert(TmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int insertSelective(TmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    List<TmallOrder> selectByExample(TmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    TmallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") TmallOrder record, @Param("example") TmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int updateByExample(@Param("record") TmallOrder record, @Param("example") TmallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int updateByPrimaryKeySelective(TmallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tmall_order
     *
     * @mbg.generated Fri Oct 04 21:50:56 CST 2019
     */
    int updateByPrimaryKey(TmallOrder record);

    /**
     * 获取指定条数未拉取订单
     *
     * @param orderCnt
     * @return
     */
    List<TmallOrder> getNotFetchedOrder(int orderCnt);
}